server:
  port: 8301
  addressip: 52baojie.cn


spring:
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
    mode: LEGACYHTML5
    encoding: utf-8
    servlet:
      content-type: text/html
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://${server.addressip}:3307/clean?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: aliluning
      password: root
      max-lifetime: 28770000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximum-pool-size: 10 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      minimum-idle: 5
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      connection-timeout: 0000
      connection-test-query: SELECT 1

  redis:
    host: ${server.addressip}
    password: luning
    port: 6380
    maxTotal: 500
    maxIdle: 20
    minIdle: 20
    maxWaitMillis: 3000
    numTestsPerEvictionRun: 3
    testOnBorrow: true
    database: 0
    blockWhenExhausted: true
    testOnReturn: true
  data:
    mongodb:
      uri: mongodb://clean:clean@${server.addressip}:27017/clean

  rabbitmq:
    host: ${server.addressip}
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    publisher-confirms: true #支持发布确认
    publisher-returns: true  #支持发布返回
    listener:
      simple:
        acknowledge-mode: manual #开启重试
        retry:
          max-attempts: 3 #重试次数
          enabled: true #开启重试
          initial-interval: 5000ms #重试间隔时间（单位毫秒）
#          max-interval: 1200000 #重试最大时间间隔（单位毫秒）
          multiplier: 5 #应用于前一重试间隔的乘法器。
        default-requeue-rejected: false #重试次数超过上面的设置之后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列）
      direct:
        acknowledge-mode: manual

  mvc:
    static-path-pattern: /**
  resources:
    static-locations: /META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/webjars/

mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.clean.applet.model
  configuration:
    map-underscore-to-camel-case: true

http:
  pool:
    max-totle: 200
    max-per-route: 20
    connect-request-timeout: 5000
    connect-timeout: 5000
    socket-timeout: 61000

logging:
  config: classpath:logback-spring.xml

wx:
  appid: wx252f27b1d5b6dca5
  AppSecret: 6040ac14476b3712fec3c331e6472059
  account: zhanmengle@126.com
  passwd: 38147847qq@


timer:
  limit-apply:
    servers: 127.0.0.1:8301
    cron: 0 0/5 * * * ?

