server:
  port: 8401
  addressip: 52baojie.cn

spring:
  redis:
    host: ${server.addressip}
    password: luning
    port: 6380
    timeout: 3000ms
    lettuce:
      pool:
        min-idle: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 300
        max-wait: 1000ms
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://${server.addressip}:3307/clean?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: aliluning
      password: root
      max-lifetime: 28770000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximum-pool-size: 10 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      minimum-idle: 5
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      connection-timeout: 0000
      connection-test-query: SELECT 1


  rabbitmq:
    host: ${server.addressip}
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual

mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.applet.sms.model
  configuration:
    map-underscore-to-camel-case: true

http:
  pool:
    max-totle: 200
    max-per-route: 20
    connect-request-timeout: 5000
    connect-timeout: 5000
    socket-timeout: 61000

logging:
  config: classpath:logback-spring.xml

timer:
  sms-test:
    servers: 127.0.0.1:8501,127.0.0.1:8401
    cron: 0 0/5 * * * ?

jpush:
  app_key: f89b6de1fa040587f10002d9
  master_secre: b5727fda9dec7f85893486cd
  apns_production: false
  max_retry_times: 5


